# Generated by Django 3.2.5 on 2021-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hot',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
