# Generated by Django 3.2.5 on 2021-07-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='hot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
